name: Verification tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verification_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [p256, p384, ml-dsa]
        crypto: [rustcrypto]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache cargo registry and build
        uses: Swatinem/rust-cache@v2
      - name: build simulator
        run: cargo build -p simulator --features=${{ matrix.profile }},${{ matrix.crypto }} --no-default-features
      - name: run verification tests
        run: |
          cd verification/testing
          go test -v

